---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo 'init script' # runs during prebuild
      pip install robotframework
      pip install -r requirements.txt
    command: |
      echo 'start script'
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
  - port: 6080
    onOpen: open-browser
  - port: 8138
    onOpen: ignore
    visibility: public
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
